#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

CONFIG_FILE='/opt/zookeeper/conf/zoo.cfg'

# Tick time:
: ${ZK_TICK_TIME:-2000} && \
echo "tickTime=${ZK_TICK_TIME}" > ${CONFIG_FILE}

# Data dir:
: ${ZK_DATA_DIR:-/var/lib/zookeeper} && \
echo "dataDir=${ZK_DATA_DIR}" >> ${CONFIG_FILE}

# My ID:
: ${ZK_SERVER_ID} && \
echo "${ZK_SERVER_ID}" > ${ZK_DATA_DIR}/myid

# Client port:
: ${ZK_CLIENT_PORT:-2181} && \
echo "clientPort=${ZK_CLIENT_PORT}" >> ${CONFIG_FILE}

# Init limit:
: ${ZK_INIT_LIMIT:-5} && \
echo "initLimit=${ZK_INIT_LIMIT}" >> ${CONFIG_FILE}

# Sync limit:
: ${ZK_SYNC_LIMIT:-2} && \
echo "syncLimit=${ZK_SYNC_LIMIT}" >> ${CONFIG_FILE}

# Client port address:
: ${ZK_CLIENT_PORT_ADDRESS:-0.0.0.0} && \
echo "clientPortAddress=${ZK_CLIENT_PORT_ADDRESS}" >> ${CONFIG_FILE}

# Peers server list:
[ "${ZK_SERVERS}" ] && {

  ID=1; IFS=',' read -ra SERVERS <<< "${ZK_SERVERS}"

  for i in "${SERVERS[@]}"; do
    echo "server.${ID}=${i}:2888:3888" >> ${CONFIG_FILE}
    ID=$((ID + 1))
  done
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

cat ${CONFIG_FILE}
exec /opt/zookeeper/bin/zkServer.sh start-foreground
