#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

# Setup this server ID:
echo "[Init] Configuring this server ID as '${ZK_SERVER_NUMBER}'"
[ "${ZK_SERVER_NUMBER}" ] && {
  [ -d /data ] || mkdir /data
  echo "${ZK_SERVER_NUMBER}" > /data/myid
}

# Setup the full peers server list:
[ "${ZK_SERVERS}" ] && {

  OIFS=${IFS}; IFS=','; ID=1
  read -ra SERVERS <<< "${ZK_SERVERS}"

  for server in "${SERVERS[@]}"; do
    echo "[Init] Configuring '${server}:2888:3888' peer...'"
    echo "server.${ID}=${server}:2888:3888" >> /opt/zookeeper-3.4.6/conf/zoo.cfg
    ID=$((ID + 1))
  done

  IFS=${OIFS}
}

# Disable JMX:
export JMXDISABLE=true

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
