#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

CONFIG_FILE='/opt/zookeeper/conf/zoo.cfg'

# Data dir:
: ${ZK_DATA_DIR:-/data} && \
echo "dataDir=${ZK_DATA_DIR}" > ${CONFIG_FILE}

# Client port:
: ${ZK_CLIENT_PORT:-2181} && \
echo "clientPort=${ZK_CLIENT_PORT}" >> ${CONFIG_FILE}

# Client port address:
: ${ZK_CLIENT_PORT_ADDRESS:-0.0.0.0} && \
echo "clientPortAddress=${ZK_CLIENT_PORT_ADDRESS}" >> ${CONFIG_FILE}

# Peers server list:
[ "${ZK_SERVERS}" ] && {

  ID=1; IFS=',' read -ra SERVERS <<< "${ZK_SERVERS}"

  for i in "${SERVERS[@]}"; do
    echo "server.${ID}=${i}:2888:3888" >> ${CONFIG_FILE}
    ID=$((ID + 1))
  done
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

exec /opt/zookeeper/bin/zkServer.sh start-foreground
